export const restaurantMockData = [
  {
    id: 1,
    restaurantName: "By Behrouz Biryani - Royal & Safe",
    dish: "Subz-E-Biryani [ Veg Biryani Serves 1]",
    description:
      "[Served with 1 Gulab Jamun & Mint Raita] Adorned with fresh vegetables, golden-hued long-grain basmati, & the coveted Behrouz spice mix, this dish will lend you an experience unlike any other.",
    rupees: "315",
    img: "",
    rating: "4.1",
    veg: true,
    deliveryTime: 37,
    isFastDelivery: true,
    count: 0,
  },
  {
    id: 2,
    restaurantName: "By Muradabadi Shahi Biryani (Tilak Nagar)",
    dish: "Chicken Biryani",
    description:
      "A delightfully hearty meal with a flavor-packed creamy butter chicken , made to perfection",
    rupees: "100",
    img: "",
    rating: "4.0",
    veg: false,
    deliveryTime: 32,
    isFastDelivery: false,
    count: 0,
  },
  {
    id: 3,
    restaurantName: "By Chawla Kitchen",
    dish: "Chicken Biryani",
    description:
      "| Serve 1 -2 , 2 Chicken Pcs | | Served with Curry/Gravy (175ml)",
    rupees: "340",
    img: "",
    rating: "3.9",
    veg: true,
    deliveryTime: 25,
    isFastDelivery: true,
    count: 0,
  },
  {
    id: 4,
    restaurantName: "By Creme N Crisp",
    dish: "HOT GULAB JAMUN 2PCS",
    description:
      "| Serve 1 -2 , 2 Chicken Pcs | | Served with Curry/Gravy (175ml)",
    rupees: "64",
    img: "",
    rating: "4",
    veg: true,
    deliveryTime: 27,
    isFastDelivery: true,
    count: 0,
  },
  {
    id: 5,
    restaurantName: "By Hira Sweets",
    dish: "Gulab Jamun (500 Gms)",
    description:
      "Gulab jamun is an Indian sweet made with milk solids. These fried balls are",
    rupees: "220",
    img: "",
    rating: "4.1",
    veg: true,
    deliveryTime: 45,
    isFastDelivery: false,
    count: 0,
  },
  {
    id: 6,
    restaurantName: "By Sunil Momos.Com",
    dish: "Veg Steamed Momos",
    description:
      "Momos are awesome",
    rupees: "80",
    img: "",
    rating: "3.9",
    veg: true,
    deliveryTime: 19,
    isFastDelivery: true,
    count: 0,
  },
  {
    id: 7,
    restaurantName: "By The Momo Chutney",
    dish: "Chicken Steam Momos",
    description:
      "Chicken momos is a north eastern recipe and very popular in tibet as well.",
    rupees: "340",
    img: "",
    rating: "3.9",
    veg: false,
    deliveryTime: 50,
    isFastDelivery: false,
    count: 0,
  },
  {
    id: 8,
    restaurantName: "By Unique Tasty Bites (Kirti Nagar)",
    dish: "Veg Steam Momos",
    description:
      "Momossss",
    rupees: "70",
    img: "",
    rating: "3.9",
    veg: false,
    deliveryTime: 37,
    isFastDelivery: true,
    count:0
  },{
    id: 9,
    restaurantName: "By Sethi Restaurant",
    dish: "Shahi Paneer",
    description:
      "A rich, creamy curry of soft succulent paneer and plenty of onions in a wonderful medley",
    rupees: "250",
    img: "",
    rating: "4",
    veg: true,
    deliveryTime: 25,
    isFastDelivery: true,
    count:0
  },{
    id: 10,
    restaurantName: "By Punjabi Angithi",
    dish: "Paneer Lababdar",
    description:
      "Combination of cottage cheese and exotic gravy made from tomato puree,",
    rupees: "195",
    img: "",
    rating: "4.1",
    veg: true,
    deliveryTime: 30,
    isFastDelivery: false,
    count:0
  }
];
